# Generated by Django 4.1.13 on 2026-03-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
