# Generated by Django 4.1.13 on 2026-02-28 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('project', 'user')},
        ),
    ]
